library(readr)
framingham <- read_csv("C:/Users/Neal/Downloads/framingham.csv")
View(framingham)
str(framingham)
library("caTools")
set.seed(1000)
split= sample.split(framingham$TenYearCHD,SplitRatio = 0.65)
train= subset(framingham, split==TRUE)
test= subset(framingham, split==FALSE)
framinghamLog=glm(TenYearCHD~., data= train,family= binomial)
#starts show how significant that variable is to the model
summary(framinghamLog)
predictTest<- predict(framinghamLog, type="response",newdata=test)
table(test$TenYearCHD, predictTest >0.5)
install.packages("ROCR")
library("ROCR")
ROCRpred<-prediction(predictTest, test$TenYearCHD)
#gives auc values on testing set, model can differenciate b/w low risk and high risk well
as.numeric(performance(ROCRpred,"auc")@y.values)
